apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: db2-debezium-connector
  namespace: db2
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.debezium.connector.db2.Db2Connector
  config:
    database.dbname: sample
    database.history.kafka.bootstrap.servers: my-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: cdc
    database.hostname: db2
    database.include.list: db2inst1.department
    database.password: password
    database.port: 50000
    database.server.name: db2inst1
    database.user: db2inst1
  tasksMax: 1
