apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: postgresql-sink-connector
  namespace: db2
  labels:
    strimzi.io/cluster: my-connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  config:
    auto.create: true
    connection.url: jdbc:postgresql://postgresql:5432/sampledb?user=userOY8&password=XHNSh4vlGX5viVsR
    topics.regex: db2.*
    transforms: unwrap
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
  tasksMax: 2
